use std::collections::HashMap;

fn main() {

    //--------
    // Vector
    //--------

    let v: Vec<i32> = Vec::new();

    //----------

    // If you create a Vec<T> with initial values, and Rust will infer the type of 
    // value you want to store
    let v = vec![1, 2, 3];

    //----------

    // If we want to be able to change its value, we need to make it mutable using 
    // the `mut` keyword

    // The numbers we place inside are all of type i32, and Rust infers this from the 
    // data, so we don’t need the Vec<i32> annotation

    let mut v = Vec::new();

    v.push(5);
    v.push(6);
    v.push(7);
    v.push(8);

    // A pop method removes and returns the last element
    v.pop();

    //----------

    // Using `&` and `[]` gives us a reference to the element at the index value

    let third: &i32 = &v[2];

    // ❌ You can’t have mutable and immutable references in the same scope
    // v.push(6);

    println!("The third element is {third}");

    // When we use the `get` method with the index passed as an argument, we get an 
    // `Option<&T>`

    let third: Option<&i32> = v.get(2);
    match third {
        Some(third) => println!("The third element is {third}"),
        None        => println!("There is no third element."),
    }

    //---------------------------------------
    // Iterating Over the Values in a Vector

    for i in &v {
        println!("{i}");
    }

    // Iterate over mutable references to each element in a mutable vector in order to 
    // make changes to all the elements

    for i in &mut v {
        *i += 50;
    }

    //---------------------------------------
    // Using an Enum to Store Multiple Types

    enum SpreadsheetCell {
        Int(i32),
        Float(f64),
        Text(String),
    }

    // Rust needs to know what types will be in the vector at compile time so that it 
    // knows exactly how much memory on the heap will be needed to store each element

    let row = vec![
        SpreadsheetCell::Int(3),
        SpreadsheetCell::Text(String::from("blue")),
        SpreadsheetCell::Float(10.12),
    ];

    //--------
    // String
    //--------

    let mut s = String::new();
    s.push_str("foo");

    // If we have some initial data with which we want to start the string, we use the 
    // `to_string` method,
    let data = "initial contents";
    let s = data.to_string();

    let s = "initial contents".to_string();

    // We can use the function `String::from` to create a String from a string literal
    let s = String::from("initial contents");

    //-------------------
    // Updating a string

    let mut s = String::from("foo");
    s.push_str("bar");
    s.push('l');

    println!("{s}");

    //----------------------
    // Concatenating with +

    let s1 = String::from("Hello, ");
    let s2 = String::from("world!");

    // The + operator uses the add method, whose signature looks something like this:
    //   fn add(self, s: &str) -> String {

    // 1. The signature of `add` takes ownership of `self` because `self` does not have
    //    an `&`. This means `s1` will be moved into the `add` call and will no longer 
    //    be valid after that
    // 2. `s2` has an `&`, meaning that we're adding a reference of the second string 
    //     to the first string

    let s3 = s1 + &s2; // Note: s1 has been moved here and can no longer be used
    println!("{s3}");

    //----------------------------
    // Concatenating with format!

    let s1 = String::from("Hello, ");
    let s2 = String::from("world!");

    // The code using `format!` is much easier to read, and the code generated by the 
    // `format!` macro uses references so that this call doesn’t take ownership of any 
    // of its parameters.

    let s3 = format!("{s1}{s2}");
    println!("{s3}");

    //-----------------------
    // Indexing into Strings

    // ❌ Rust strings don’t support indexing
    // let h = s3[0];

    //------------------------
    // Iterating Over Strings

    for c in "Зд".chars() {
        println!("{c}");
    }

    for b in "Зд".bytes() {
        println!("{b}");
    }

    //----------
    // Hash map
    //----------

    let mut scores = HashMap::new();

    // Hash maps are homogeneous: All of the keys must have the same type, and all of 
    // the values must have the same type

    scores.insert(String::from("Blue"), 10);
    scores.insert(String::from("Yellow"), 50);

    let team_name = String::from("Blue");
    let score = scores
                    .get(&team_name) // `get` method returns an `Option<&V>`
                    .copied()        // Get an `Option<i32>` rather than an `Option<&i32>`
                    .unwrap_or(0);   // Set `score` to zero if scores doesn’t have an entry
                                     // for the key.

    println!("Score: {score}");

    for (key, value) in &scores {
        println!("{key}: {value}");
    }

    //---------------------------------
    // Managing Ownership in Hash Maps

    let field_name = String::from("Favorite color");
    let field_value = String::from("Blue");

    let mut map = HashMap::new();
    map.insert(field_name, field_value);

    // `field_name` and `field_value` are invalid at this point.
    // They’ve been moved into the hash map

    // If we insert references to values into the hash map, the values won’t be moved into
    // the hash map. The values that the references point to must be valid for at least as
    // long as the hash map is valid.

    //---------------------
    // Updating a Hash Map

    // 1. Overwriting a Value

    scores.insert(String::from("Blue"), 10);
    scores.insert(String::from("Blue"), 25);

    // 2. Adding a Key and Value Only If a Key Isn’t Present

    scores
        .entry(String::from("Blue")) // The return value is an enum called Entry that 
                                     // represents a value that might or might not exist
        .or_insert(50); // Return a mutable reference to the value for the corresponding 
                        // `Entry` key if that key exists, and if not, it inserts the 
                        // parameter as the new value for this key and returns a mutable 
                        // reference to the new value
    
    // 3. Updating a Value Based on the Old Value

    let text = "hello world wonderful world";

    let mut map = HashMap::new();

    for word in text.split_whitespace() {
        let count = map.entry(word).or_insert(0);
        *count += 1;
    }

    println!("{map:?}");

}

//--------------------
// Sample application

/*
 * 1. Given a list of integers, use a vector and return the median (when sorted, the value
 *    in the middle position) and mode (the value that occurs most often; a hash map will 
 *    be helpful here) of the list.
 */
pub fn median_and_mode(numbers: &[i32]) -> Option<(f64, i32)> {
    if numbers.is_empty() {
        return None;
    }

    // 1. Calculate Median
    // We clone the slice into a vector because we need to sort it, 
    // and we shouldn't mutate the original input slice.
    let mut sorted = numbers.to_vec();
    sorted.sort_unstable(); 

    let len = sorted.len();
    let mid = len / 2;
    
    let median = if len % 2 == 0 {
        // Average the two middle numbers if the length is even
        (sorted[mid - 1] as f64 + sorted[mid] as f64) / 2.0
    } else {
        // Otherwise, grab the exact middle
        sorted[mid] as f64
    };

    // 2. Calculate Mode
    let mut frequencies = HashMap::new();
    for &num in numbers {
        // or_insert(0) inserts 0 if the key doesn't exist, 
        // then returns a mutable reference to the value so we can add 1.
        *frequencies.entry(num).or_insert(0) += 1;
    }

    // Find the key with the highest value (count)
    let mode = frequencies

        // This converts the HashMap into an iterator. Because it's a map, the iterator 
        // yields each entry as a tuple containing the key and the value.
        .into_iter()

        // The closure `|&(_, count)|`: This takes a reference to the current tuple being 
        // evaluated. We use pattern matching to destructure it. The closure returns `count`

        // `max_by_key` returns an `Option` containing the entire winning tuple
        .max_by_key(|&(_, count)| count)

        // The closure `|(val, _)| val` ignores the count and returns just the value
        .map(|(val, _)| val)

        // We can safely unwrap here because we know the list isn't empty
        .unwrap(); 

    Some((median, mode))
}

/*
 * 2. Convert strings to Pig Latin. The first consonant of each word is moved to the end of 
 *    the word and ay is added, so first becomes irst-fay. Words that start with a vowel have
 *    hay added to the end instead (apple becomes apple-hay). Keep in mind the details about 
 *    UTF-8 encoding!
 */
fn is_vowel(c: char) -> bool {
    matches!(c, 'a' | 'e' | 'i' | 'o' | 'u' | 'A' | 'E' | 'I' | 'O' | 'U')
}

/// Converts a single word to Pig Latin.
pub fn convert_word(word: &str) -> String {
    let mut chars = word.chars();

    // Safely get the first character as a `char` (handles multi-byte UTF-8)
    let first_char = match chars.next() {
        Some(c) => c,
        None => return String::new(),
    };

    if is_vowel(first_char) {
        format!("{word}-hay")
    } else {
        // `chars.as_str()` returns a `&str` slice of all *remaining* characters.
        // Because it comes directly from the `Chars` iterator, it is guaranteed 
        // to land on a valid UTF-8 boundary.
        format!("{}-{}ay", chars.as_str(), first_char)
    }
}

/// Converts an entire sentence to Pig Latin.
pub fn to_pig_latin(text: &str) -> String {
    text.split_whitespace()
        .map(convert_word)
        .collect::<Vec<_>>()
        .join(" ")
}

/*
 * 3. Using a hash map and vectors, create a text interface to allow a user to add employee 
 *    names to a department in a company; for example, “Add Sally to Engineering” or “Add 
 *    Amir to Sales.” Then, let the user retrieve a list of all people in a department or all
 *    people in the company by department, sorted alphabetically.
 */
#[derive(Default)]
struct Company {
    // Map where Key = Department Name, Value = List of Employee Names
    departments: HashMap<String, Vec<String>>,
}

impl Company {

    // The `Self` keywords in the return type and in the body of the function are aliases for the type that appears
    // after the `impl` keyword
    fn new() -> Self {
        Self {
            departments: HashMap::new(),
        }
    }

    /// Adds an employee to a given department.
    fn add_employee(&mut self, name: &str, department: &str) {
        // `entry` gets or creates the key, `or_default` initializes an empty Vec
        self.departments
            .entry(department.to_string())
            .or_default()
            .push(name.to_string());
    }

    /// Returns a sorted vector of employee names for a specific department.
    fn get_department(&self, department: &str) -> Option<Vec<&str>> {
        self.departments.get(department).map(|employees| {
            let mut sorted: Vec<&str> = employees.iter().map(AsRef::as_ref).collect();
            sorted.sort_unstable();
            sorted
        })
    }

    /// Returns all departments and their employees, both sorted alphabetically.
    fn get_all(&self) -> Vec<(&str, Vec<&str>)> {
        let mut sorted_departments: Vec<&str> = self.departments.keys().map(AsRef::as_ref).collect();
        sorted_departments.sort_unstable();

        sorted_departments
            .into_iter()
            .map(|dept| {
                let mut employees: Vec<&str> =
                    self.departments[dept].iter().map(AsRef::as_ref).collect();
                employees.sort_unstable();
                (dept, employees)
            })
            .collect()
    }
}
